on: push
name: Test
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.0', '7.1', '7.2', '7.3', '7.4' ]

    continue-on-error: ${{ matrix.php == '7.4' }}

    steps:
      - uses: actions/checkout@master

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug2

      - name: Install Dependencies
        env:
          COMPOSER_FLAGS: ${{ (matrix.php == '7.4') && ' --ignore-platform-reqs' || '' }}
        run: |
          composer install $COMPOSER_FLAGS

      - name: Test
        run: |
          php -d error_reporting=$(php -r 'echo E_ALL & ~ E_DEPRECATED & ~ E_NOTICE;') \
              -d xdebug.mode=coverage \
              -d xdebug.overload_var_dump=0 \
              vendor/bin/phpunit

      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_PARALLEL:   true
          COVERALLS_FLAG_NAME:  PHP ${{ matrix.php }}
        run: |
          composer global require php-coveralls/php-coveralls
          php-coveralls --coverage_clover=build/logs/clover.xml -v

  coveralls-webhook:
    # @see https://github.com/php-coveralls/php-coveralls#parallel-builds
    # @see https://docs.coveralls.io/parallel-build-webhook
    name:    Merge Coveralls parallel build results
    runs-on: ubuntu-latest
    needs:   test
    steps:
      - run: curl https://coveralls.io/webhook?repo_token=${{ secrets.GITHUB_TOKEN }}
